#!/bin/sh

# to comment out the entire file

if [ "$#" -ne 1 ] ; then
	echo "$0: exactly 1 argument is expected"
	exit 3
fi

get_pwd=$(pwd)
cd ~
if [ -f ~/.wgetrc ]; then
	wget_proxy_path=".wgetrc"
fi

if [ -f /etc/apt/apt.conf.d/80proxy ]; then
	apt_proxy_path="/etc/apt/apt.conf.d/80proxy"
fi


# for adding comments and turning global proxy OFF
if [ $1 = 'off' ];
then	echo "Turning proxy off ...."
	gsettings set org.gnome.system.proxy mode none
	sudo sed -i 's/^/#/' "$wget_proxy_path" "$apt_proxy_path"
fi

# for removing comments and turning global proxy ON
if [ $1 = "on" ];
then	echo "turning proxy on...."
	gsettings set org.gnome.system.proxy mode manual
	sudo sed -i 's/#//' "$wget_proxy_path" "$apt_proxy_path"
fi







